# Generated by Django 4.0.6 on 2022-07-14 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notificarion", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="notificationprice",
            name="email",
            field=models.EmailField(default="r@R.COM", max_length=254),
        ),
        migrations.AlterField(
            model_name="notificationprice",
            name="name",
            field=models.CharField(default="", max_length=100),
        ),
    ]
